### ISSUE TITLE
flatMap未正确转为对应的兼容方法

### ISSUE THREAD

**Issue by timburg2000** [xlfsummer/beat-saber-version-transformer#1]
从贴吧来的，您好像一直没再回贴吧

现在的链接出现问题了，
beat-saber-version-transformer.xlf-summer.cn/
无法上传文件夹，只能上传文件。
但是上传文件后会报错
上传压缩包也不行。
问题详情可以看吧友的回复：
https://tieba.baidu.com/p/6160106455

万分期望您能抽时间修复该问题
万分感谢！

**Comment by xlfsummer** [comment]
这个问题我看到了，但这两天没时间解决。
关于上传文件：
新版本取消了文件夹上传，支持了单个/多个zip上传。
关于上传会报错：
代码中使用了较新的方法，但框架的依赖包版本不支持把它转为较旧的方法。大家使用的浏览器也不支持这个特性，于是导致了报错。

关于解决方案，前两天看了一下，没找到，后续我还会再看。

目前大家可以把 chrome 浏览器升级到最新版本来使用，最新的 chrome 浏览器是支持这个特性的。

**Comment by timburg2000** [comment]
> 这个问题我看到了，但这两天没时间解决。
> 关于上传文件：
> 新版本取消了文件夹上传，支持了单个/多个zip上传。
> 关于上传会报错：
> 代码中使用了较新的方法，但框架的依赖包版本不支持把它转为较旧的方法。大家使用的浏览器也不支持这个特性，于是导致了报错。
> 
> 关于解决方案，前两天看了一下，没找到，后续我还会再看。
> 
> 目前大家可以把 chrome 浏览器升级到最新版本来使用，最新的 chrome 浏览器是支持这个特性的。

不知道是不是有别的其他原因。。我的chrome浏览器的设置里面已经显示是最新版本（75.0.3770.100（正式版本） （64 位））。
上传单个/多个zip虽然不会直接报错，但是选择zip并点击“打开”后，原页面没有任何反应。。
依然是“NOTHING CHOOSED”和“NOTHING SELECT”

**Comment by xlfsummer** [comment]
@gaosonginChina 我在上周更新的网页中已经加了错误检测，可以捕获全局错误并且显示一个带调试信息的弹窗。如果你没有看到错误弹窗，可能是两个原因：
1. 网页不是最新副本
- 尝试使用  <kbd>Ctrl</kbd>+<kbd>F5</kbd> 强制刷新页面，然后再次尝试上传。如果程序抛出了异常，把弹窗中的调试信息复制出来，发到这里。
2. 错误被异常的捕获了
- 进入页面，首先按 <kbd>F12</kbd> 打开开发者工具，打开 console 面板，然后上传文件，查看开发者工具里是否打印出了错误信息，把它截图/复制发出来。

如果上面两种方法都不行，可以把zip文件上传到 issue 里，我这边来调试。

**Comment by timburg2000** [comment]
> @gaosonginChina 我在上周更新的网页中已经加了错误检测，可以捕获全局错误并且显示一个带调试信息的弹窗。如果你没有看到错误弹窗，可能是两个原因：
> 
> 1. 网页不是最新副本
> 
> * 尝试使用  Ctrl+F5 强制刷新页面，然后再次尝试上传。如果程序抛出了异常，把弹窗中的调试信息复制出来，发到这里。
> 
> 1. 错误被异常的捕获了
> 
> * 进入页面，首先按 F12 打开开发者工具，打开 console 面板，然后上传文件，查看开发者工具里是否打印出了错误信息，把它截图/复制发出来。
> 
> 如果上面两种方法都不行，可以把zip文件上传到 issue 里，我这边来调试。

1.尝试了ctrl+f5强制刷新页面，并再次尝试上传，但后续跟之前完全一样，没有弹窗。
2.点击上传后，console面板中的错误信息如下：
![bug](https://user-images.githubusercontent.com/50735490/60011494-7865f580-96ac-11e9-993a-984cd9a795bb.png)

**Comment by xlfsummer** [comment]
@gaosonginChina 这可能是在播放音乐时，音频格式无法识别错误导致的，检查你的 zip 文件夹中是否存在以 ogg 结尾的音频文件，然后把 zip 包上传到 issue #2 里。麻烦移步 #2 继续讨论这个 issue。

**Comment by xlfsummer** [comment]
Fix in commit 058ac236261e32b1b7aaa47314bed2e277f48141
