### ISSUE TITLE
需要添加批处理！

### ISSUE THREAD

**Issue by Lakr233** [xlfsummer/beat-saber-version-transformer#3]
是这样的因为有好多好多歌曲要升级很麻烦我就开了个fork稍微修改了一下添加了批处理给自己用

但是小白们也需要这个功能啊！（逃
如果可以的话还请再开个二级域名方便小白们使用

**Comment by xlfsummer** [comment]
你可以提交一个PR，我来合并

**Comment by xlfsummer** [comment]
fix in be17072a2b42b5184a559ed557208824cbf9e8b3
已经发布
